server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  application:
    name: Usuarios
  datasource:
    url: jdbc:mysql://localhost:3306/digitalmoneyhouse
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: digital
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  zipkin:
    base-url: http://localhost:9411/
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
queue: # llave de configuración para conocer cómo se llama la cola
  movie:
    name: ColaUsuarios
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: false
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.session: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security.web.csrf: DEBUG
    org.springframework.security.web.authentication.rememberme: DEBUG